import NamedSection from "@/components/Typography/NamedSection";
import NamedSubSection from "@/components/Typography/NamedSubSection";
import Para from "@/components/Typography/Para";
import Bold from "@/components/Typography/Bold";

const page = () => {
  return (
    <main className="p-[20px] flex flex-col gap-4 w-full px-[20px] site-container mx-auto text-justify">
      <Para>
        This End User Agreement (the “Agreement”) is made between you (the
        “User” or “You”) and Nest Money (Legentree Technologies Pvt Ltd)
        (“CLIENT”, “Us” or “We”, which term shall include its successors and
        permitted assigns). The User and CLIENT shall be collectively referred
        to as the “Parties” and individually as a “Party”.
      </Para>
      <Para>
        BY EXECUTING THIS AGREEMENT / CONSENT FORM, YOU ARE EXPRESSLY AGREEING
        TO ACCESS THE EXPERIAN CREDIT INFORMATION REPORT AND CREDIT SCORE,
        AGGREGATE SCORES, INFERENCES, REFERENCES AND DETAILS (AS DEFINED BELOW)
        (TOGETHER REFERRED AS “CREDIT INFORMATION”). YOU HEREBY ALSO CONSENT TO
        SUCH CREDIT INFORMATION BEING PROVIDED BY EXPERIAN TO YOU AND CLIENT BY
        USING EXPERIAN TOOLS, ALGORITHMS AND DEVICES AND YOU HEREBY AGREE,
        ACKNOWLEDGE AND ACCEPT THE TERMS AND CONDITIONS SET FORTH HEREIN.
      </Para>
      <NamedSection heading="Terms and Conditions : ">
        <NamedSubSection sl="1">
          Information Collection, Use, Confidentiality, No-Disclosure and Data
          Purging CLIENT shall access your Credit Information as your authorized
          representative and CLIENT shall use the Credit Information for limited
          End Use Purpose consisting of and in relation to the services proposed
          to be availed by you from CLIENT. We shall not aggregate, retain,
          store, copy, reproduce, republish, upload, post, transmit, sell or
          rent the Credit Information to any other person and the same cannot be
          copied or reproduced other than as agreed herein and in furtherance to
          CICRA.
        </NamedSubSection>
        <NamedSubSection sl="2">
          The Parties agree to protect and keep confidential the Credit
          Information both online and offline. The Credit Information shared by
          you or received on by us on your behalf shall be destroyed, purged,
          erased promptly of upon the completion of the transaction/ End Use
          Purpose for which the Credit Information report was procured for up to
          a maximum of 6 months.
        </NamedSubSection>
        <NamedSubSection sl="3">
          Governing Law and Jurisdiction The relationship between you and CLIENT
          shall be governed by laws of India and all claims or disputes arising
          there from shall be subject to the exclusive jurisdiction of the
          courts of Mumbai.
        </NamedSubSection>
      </NamedSection>
      <NamedSection heading="Definitions : ">
        <Para>
          Capitalized terms used herein but not defined above shall have the
          following meanings: “Business Day” means a day (other than a public
          holiday) on which banks are open for general business in Mumbai.
        </Para>
        <NamedSubSection sl="1">
          <Bold>“Credit Information Report”</Bold> means the credit information
          / scores/ aggregates / variables / inferences or reports which shall
          be generated by Experian;
        </NamedSubSection>

        <NamedSubSection sl="2">
          <Bold>“Credit Score”</Bold> means the score which shall be mentioned
          on the Credit Information Report which shall be computed by Experian.
        </NamedSubSection>
        <NamedSubSection sl="3">
          <Bold>“CICRA”</Bold> shall mean the Credit Information Companies
          (Regulation) Act, 2005 read with the Credit Information Companies
          Rules, 2006 and the Credit Information Companies Regulations, 2006,
          and shall include any other rules and regulations prescribed
          thereunder.
        </NamedSubSection>
      </NamedSection>

      <Para>
        Please read the above mentioned terms and conditions and click on the
        tick box to complete the authorisation process
        <br /> ** This document is an electronic record in terms of the
        Information Technology Act, 2000 and Rules made there under, and the
        amended provisions pertaining to electronic records.
      </Para>
    </main>
  );
};

export default page;
